In [193]:
import pandas as pd

In [194]:
import numpy as np

In [195]:
from sklearn import svm

In [196]:
from sklearn.neural_network import MLPClassifier

In [197]:
from sklearn.metrics import accuracy_score

In [198]:
from sklearn.model_selection import train_test_split

In [199]:
import warnings
warnings.filterwarnings("ignore")

In [200]:
data = pd.read_csv('processed.cleveland.data.csv')

In [201]:
columns = ['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach', 'exang', 'oldpeak', 'slope', 'ca', 'thal', 'num']
data = pd.read_csv('processed.cleveland.data.csv')
data.columns = columns
data.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
1  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
2  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
3  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   
4  56.0  1.0  2.0     120.0  236.0  0.0      0.0    178.0    0.0      0.8   

   slope   ca  thal  num  
0    2.0  3.0   3.0    2  
1    2.0  2.0   7.0    1  
2    3.0  0.0   3.0    0  
3    1.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

In [202]:
data.shape

(302, 14)

In [203]:
data.num.value_counts()

0    163
1     55
2     36
3     35
4     13
Name: num, dtype: int64

In [204]:
X = data.drop(['num'], axis=1)
y = data['num']

In [205]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [206]:
cols = X_train.columns

In [207]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [208]:
X_train = pd.DataFrame(X_train, columns=[cols])

In [209]:
X_test = pd.DataFrame(X_test, columns=[cols])

In [210]:
Task3_SVM = svm.SVC(kernel='linear', C = 1.0).fit(X_train, y_train)
y_pred_test = Task3_SVM.predict(X_test)

##SVM Model Code

In [211]:
print('Model accuracy score with linear kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_test)))

Model accuracy score with linear kernel and C=1.0 : 0.5738


In [212]:
Task3_SVM_sigmoid = svm.SVC(kernel='sigmoid').fit(X_train, y_train)
y_pred_test_sigmoid = Task3_SVM_sigmoid.predict(X_test)

In [213]:
print('Model accuracy score with sigmoid kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_test_sigmoid)))

Model accuracy score with sigmoid kernel and C=1.0 : 0.5410


In [214]:
Task3_SVM_rbf = svm.SVC(kernel='rbf').fit(X_train, y_train)
y_pred_test_rbf = Task3_SVM_rbf.predict(X_test)

In [215]:
print('Model accuracy score with rbf kernel and C=1.0 : {0:0.4f}'. format(accuracy_score(y_test, y_pred_test_rbf)))

Model accuracy score with rbf kernel and C=1.0 : 0.4754


In [216]:
y_pred_train_linear = Task3_SVM.predict(X_train)
y_pred_train_sigmoid = Task3_SVM_sigmoid.predict(X_train)
y_pred_train_rbf = Task3_SVM_rbf.predict(X_train)

##Training Set Accuracies

In [335]:
print('Training-set linear accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train_linear)))
print('Training-set sigmoid accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train_sigmoid)))
print('Training-set rbf accuracy score: {0:0.4f}'. format(accuracy_score(y_train, y_pred_train_rbf)))

Training-set linear accuracy score: 0.7261
Training-set sigmoid accuracy score: 0.6100
Training-set rbf accuracy score: 0.7676


##MLP Model Code

In [331]:
mlp = MLPClassifier(hidden_layer_sizes=(30,30,30))
mlp.activation = 'tanh'
mlp.learning_rate_init = 0.01
mlp.solver = 'sgd'
mlp.fit(X_train,y_train)

MLPClassifier(activation='tanh', hidden_layer_sizes=(30, 30, 30),
              learning_rate_init=0.01, solver='sgd')

In [332]:
predictions = mlp.predict(X_test)

In [333]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test, predictions))

[[25  4  0  0  0]
 [ 3  1  1  2  0]
 [ 3  3  3  2  0]
 [ 1  7  2  2  0]
 [ 0  0  1  1  0]]


In [334]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

           0       0.78      0.86      0.82        29
           1       0.07      0.14      0.09         7
           2       0.43      0.27      0.33        11
           3       0.29      0.17      0.21        12
           4       0.00      0.00      0.00         2

    accuracy                           0.51        61
   macro avg       0.31      0.29      0.29        61
weighted avg       0.51      0.51      0.50        61

